### ISSUE TITLE
Remove Play Configuration dependency

### ISSUE THREAD

**Issue by jorkzijlstra** [kaliber-scala/jira-exception-processor#12]
It should be possible to add this exception processor to non-Play applications. 

Replacing the Configuration with a custom case class which holds the settings should solve this.

**Comment by EECOLOR** [comment]
For ease of use we should probably split it into two libraries. `jira-exception-processor` and `play-jira-exception-processor`. The last one can depend on the first one and this should be backwards compatible. We could add aliases from the `fly.play` packages to the `net.kaliber.jiraExceptionProcessor` package.

**Comment by jorkzijlstra** [comment]
Sounds like a good plan. The Play version only needs to contain a factory method which takes a Play Configuration and returns the JiraExceptionProcessor.

**Comment by jorkzijlstra** [comment]
@EECOLOR I think we can first divide the application insode the repo in a root application which contain the play version and a sub module which contains the generic version. Then moving and releasing the generic version to a new repository should be easy.

**Comment by EECOLOR** [comment]
I think both modules should keep living inside the same repository. The [Scala Command Utilities](https://github.com/Kaliber/scala-command-utilities) repository has an example of this structure.

**Comment by jorkzijlstra** [comment]
Keeping them both a modules in a single repos or not is just a choice. Since upgrading a module to a library isn't the effort. Moving to modules is the work, but this is something I have used recently. So keeping them in a single repo is fine by me.

I did explore the code a bit on how to structure it and found [one issue](https://github.com/Kaliber/play-jira-exception-processor/blob/master/src/main/scala/fly/play/jiraExceptionProcessor/JiraExceptionProcessor.scala#L27).
The JiraExceptionProcessor creates a Mailer instance with the configuration. The Mailer construct the Keys class with the configuration which in turn is used to construct a Session which the mailer uses. 

So we need a place to go from MailSettings => Session

We can refactor the Play-Mailer [Session object](https://github.com/Kaliber/play-mailer/blob/master/src/main/scala/net/kaliber/mailer/package.scala
) and implement a case class MailSettings with all the properties that are now in Keys. So also this separation of the Play Configuration in the Play-Mailer.

or we can just implement it only this repo by defining a case class MailSettings and a method MailSettings => Mailer.

@EECOLOR what are your thoughts?

**Comment by EECOLOR** [comment]
Well, as it stands the play mailer library has a dependency on the Play Framework. So in order to remove the dependency on Play from this library all it's dependencies should be 'Play free' as well. So I think that we should remove Play from the core of the mailer library allowing the core of this library to depend on that.

**Comment by jorkzijlstra** [comment]
Play-mailer update is requested in this [Issue](https://github.com/Kaliber/play-mailer/issues/21)

**Comment by realjax** [comment]
Hi, what is the current status of this branch, is it abandoned?

**Comment by jorkzijlstra** [comment]
Hi, I'm still finalizing the branch. It has a dependency which needs to be released first (Play-mailer).

**Comment by jorkzijlstra** [comment]
@EECOLOR @realjax The scala-mailer has been released to Maven. I will update the jira-exception-processor to use this one and it will also be released to Maven.

**Comment by EECOLOR** [comment]
@jorkzijlstra Awesome!

**Comment by jorkzijlstra** [comment]
@EECOLOR @realjax I just released to Bintray

**Comment by jorkzijlstra** [comment]
It has been released to Maven
